networks:
  optical-db-network:
    name: optical-db-network
    driver: bridge
services:
  postgresdb:
    image: postgres:17
    networks:
      - optical-db-network
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=SecuredTime
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=pericard42
    healthcheck:
      test: ["CMD", "pg_isready", "--dbname", "SecuredTime", "--host", "localhost", "--port", "5432", "--username", "postgres"]
      retries: 5
      interval: 3s
      timeout: 30s
  app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    networks:
      - optical-db-network
    ports:
      - "8282:8282"
      - "8888:8888"
    depends_on:
      postgresdb:
          condition: service_healthy
    environment:
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=pericard42
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgresdb:5432/SecuredTime
