# DOCKER
quarkus.container-image.build=true
quarkus.container-image.name=optical-image
quarkus.container-image.tag=latest
quarkus.container-image.group=lovegiver

# APP
quarkus.application.name=OptiCal
quarkus.http.root-path=optime

# ENABLE SSL #
%prod.quarkus.http.ssl-port=8443
%prod.quarkus.http.ssl.certificate.files=/var/lib/certs/lovegiver.net/production/signed.crt
%prod.quarkus.http.ssl.certificate.key-files=/var/lib/certs/lovegiver.net/production/domain.key
%prod.quarkus.http.ssl.certificate.reload-period=1h

# AUTH SECURITY
quarkus.http.auth.basic=true
quarkus.http.cors=true
quarkus.http.cors.origins=/.*/
quarkus.http.cors.methods=GET,PUT,POST,PATCH,DELETE,OPTIONS,HEAD
quarkus.http.cors.headers=accept, authorization, content-type
quarkus.http.cors.exposed-headers=Content-Disposition
quarkus.http.cors.access-control-max-age=24H
quarkus.http.cors.access-control-allow-credentials=true

# DATABASE
quarkus.datasource.jdbc=true
quarkus.datasource.devservices.enabled=true
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=pericard42
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/SecuredTime

# ORM
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQLDialect

# LOGGING
quarkus.log.level=DEBUG
quarkus.log.file.encoding=utf-8
